export const ActionTypes = {
  UPDATE_PRODUCT_COUNTER: "UPDATE_PRODUCT_COUNTER",
  SET_PRODUCTS: "SET_PRODUCTS",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SET_CHECKOUT: "CHECKOUT",
  UPDATE_TRANSACTION: "UPDATE_TRANSACTION", 
  ADD_TRANSACTION: "ADD_TRANSACTION",
};
